import type { Metadata } from "next";
import { poppins } from "@/lib/font";
import "./globals.css";

import Navigation from "@/components/navbar/Navigation";
import Footer from "@/components/section/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navigation />

        {children}
        <Footer />
      </body>
    </html>
  );
}
